In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [2]:
from __future__ import absolute_import, division, \
    print_function, unicode_literals

In [3]:
import tensorflow as tf

In [4]:
# Enable eager execution.
tf.enable_eager_execution()

In [6]:
# Tensors
# A tensor is a multi-dimensional array. Similar to NumPy ndarray
# object, Tensor objects have a data type and a shape. 
# Additionally, Tensors can reside in accelerator (e.g. GPU)
# memory. TF operations that consume and produce Tensors
# automatically convert native Python types.
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)


In [7]:
print(tf.square(5))

tf.Tensor(25, shape=(), dtype=int32)


In [8]:
print(tf.reduce_sum([1,2,3]))

tf.Tensor(6, shape=(), dtype=int32)


In [9]:
print(tf.encode_base64('hello world'))

tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)


In [10]:
# Operator overloading is also supported.
print(tf.square(2) + tf.square(3))

tf.Tensor(13, shape=(), dtype=int32)


In [11]:
# Each Tensor has a shape and a datatype.
x = tf.matmul([[1]], [[2,3]])

In [12]:
print(x.shape, x.dtype)

(1, 2) <dtype: 'int32'>


In [13]:
# Differences between NumPy arrays and TF Tensors:
# - Tensors can be backed by accelerator memory (e.g. GPU, TPU)
# - Tensors are immutable.

In [15]:
# TF operations automatically convert np ndarrays to Tensors.
# NP operations automatically convert Tensors to NP ndarrays.
# Tensors can be explicitly converted to NP ndarrays by invoking
# the .numpy() method on them.

In [16]:
import numpy as np

In [17]:
ndarray = np.ones([3,3])

In [19]:
print("TF ops convert numpy arrays to Tensors automatically.")
tensor = tf.multiply(ndarray, 42)
print(tensor)

TF ops convert numpy arrays to Tensors automatically.
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


In [20]:
print("And NumPy ops convert Tensors to NP arrays automatically")
print(np.add(tensor,1))

And NumPy ops convert Tensors to NP arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]


In [21]:
print("The .numpy() method explicitly converts a tensor to a numpy array")
print(tensor.numpy())

The .numpy() method explicitly converts a tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [22]:
# GPU acceleration
x = tf.random.uniform([3,3])

In [23]:
print("Is there a GPU available: ")
print(tf.test.is_gpu_available())

Is there a GPU available: 
False


In [24]:
# Explicit device placement
import time

In [25]:
def time_matmul(x):
    start = time.time()
    for loop in range(10):
        tf.matmul(x,x)
    result = time.time() - start
    print("10 loops: {:0.2f}ms".format(1000*result))

In [26]:
# Force execution on CPU
print("On CPU:")
with tf.device("CPU:0"):
    x = tf.random_uniform([1000,1000])
    assert x.device.endswith("CPU:0")
    time_matmul(x)

On CPU:
10 loops: 2071.74ms


In [27]:
# Datasets
# Datasets API recommended for building performant, complex input
# pipelines from simple, re-usable pieces that will feed your
# model's training or evaluation loops.

In [28]:
# Create a source dataset using:
# - Dataset.from_tensors
# - Dataset.from_tensor_slices
# or objects that read from files like
# - TextLineDataset
# - TFRecordDataset

In [29]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])

In [30]:
# Create a CSV file
import tempfile

In [31]:
_, filename = tempfile.mkstemp()

In [32]:
with open(filename, 'w') as f:
    f.write("""Line 1
    Line 2
    Line 3
    """)
ds_file = tf.data.TextLineDataset(filename)

In [34]:
# Apply transformations
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)

In [37]:
ds_file = ds_file.batch(2)

In [38]:
# Iterate
# When eager execution is enabled, Dataset objects support
# iteration.

In [39]:
print("Elements of ds_tensors:")
for x in ds_tensors:
    print(x)
print('\nElements in ds_file:')
for x in ds_file:
    print(x)

Elements of ds_tensors:
tf.Tensor([1 9], shape=(2,), dtype=int32)
tf.Tensor([ 4 16], shape=(2,), dtype=int32)
tf.Tensor([25 36], shape=(2,), dtype=int32)

Elements in ds_file:
tf.Tensor([b'Line 1' b'    Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'    Line 3' b'    '], shape=(2,), dtype=string)
