In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [2]:
from __future__ import absolute_import, division,\
    print_function, unicode_literals
import tensorflow as tf

In [3]:
tf.enable_eager_execution()

In [4]:
# Layers: common sets of useful operations
# tf.keras.layers: layers are objects.
layer = tf.keras.layers.Dense(100)

In [5]:
# The number of input dims is often unnecessary, as it can be
# inferred the first time the layer is used.
layer = tf.keras.layers.Dense(10, input_shape=(None,5))

In [6]:
layer

In [7]:
# To use a layer, call it.
layer(tf.zeros([10,5]))

<tf.Tensor: id=29, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [9]:
# Layers have useful methods.
# A fully connected layer will have variables for weights and
# biases.
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.11698973, -0.40978748, -0.15575102, -0.07686478, -0.11220509,
         -0.5004974 , -0.37518993,  0.5264124 ,  0.0782879 ,  0.03728038],
        [ 0.06020194, -0.33296552, -0.55596924, -0.02276391,  0.34957707,
          0.36000067,  0.30563694, -0.26927745,  0.4839551 ,  0.586412  ],
        [ 0.5306744 , -0.58408856,  0.08514023, -0.59632134,  0.36120814,
         -0.6149041 ,  0.03891689,  0.4409142 , -0.02402449, -0.00808805],
        [-0.13605976, -0.03954399,  0.33443075, -0.3553173 , -0.03552336,
          0.523565  ,  0.6246595 , -0.16009617,  0.19816482, -0.3602668 ],
        [ 0.3887003 , -0.5373872 , -0.6118879 ,  0.25576448, -0.41736734,
          0.48804277,  0.07948005, -0.43688533, -0.5897317 , -0.62595624]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [10]:
layer.trainable_variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.11698973, -0.40978748, -0.15575102, -0.07686478, -0.11220509,
         -0.5004974 , -0.37518993,  0.5264124 ,  0.0782879 ,  0.03728038],
        [ 0.06020194, -0.33296552, -0.55596924, -0.02276391,  0.34957707,
          0.36000067,  0.30563694, -0.26927745,  0.4839551 ,  0.586412  ],
        [ 0.5306744 , -0.58408856,  0.08514023, -0.59632134,  0.36120814,
         -0.6149041 ,  0.03891689,  0.4409142 , -0.02402449, -0.00808805],
        [-0.13605976, -0.03954399,  0.33443075, -0.3553173 , -0.03552336,
          0.523565  ,  0.6246595 , -0.16009617,  0.19816482, -0.3602668 ],
        [ 0.3887003 , -0.5373872 , -0.6118879 ,  0.25576448, -0.41736734,
          0.48804277,  0.07948005, -0.43688533, -0.5897317 , -0.62595624]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [11]:
layer.kernel, layer.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.11698973, -0.40978748, -0.15575102, -0.07686478, -0.11220509,
         -0.5004974 , -0.37518993,  0.5264124 ,  0.0782879 ,  0.03728038],
        [ 0.06020194, -0.33296552, -0.55596924, -0.02276391,  0.34957707,
          0.36000067,  0.30563694, -0.26927745,  0.4839551 ,  0.586412  ],
        [ 0.5306744 , -0.58408856,  0.08514023, -0.59632134,  0.36120814,
         -0.6149041 ,  0.03891689,  0.4409142 , -0.02402449, -0.00808805],
        [-0.13605976, -0.03954399,  0.33443075, -0.3553173 , -0.03552336,
          0.523565  ,  0.6246595 , -0.16009617,  0.19816482, -0.3602668 ],
        [ 0.3887003 , -0.5373872 , -0.6118879 ,  0.25576448, -0.41736734,
          0.48804277,  0.07948005, -0.43688533, -0.5897317 , -0.62595624]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [12]:
# Implementing custom layers
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
    def build(self, input_shape):
        self.kernel = self.add_variable("kernel",\
                shape=[int(input_shape[-1]),self.num_outputs])
    def call(self, input):
        return tf.matmul(input, self.kernel)

In [13]:
layer = MyDenseLayer(10)

In [15]:
print(layer(tf.zeros([10,5])))
print(layer.trainable_variables)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.58729947, -0.07697213, -0.07424951,  0.30938798, -0.13261545,
        -0.24907985, -0.56485647,  0.13228023, -0.103926  , -0.1910319 ],
       [-0.55848485,  0.5300159 , -0.41020727, -0.26590174,  0.5016195 ,
        -0.43947935, -0.34729818,  0.22473437, -0.31708485, -0.41145775],
       [ 0.5009075 ,  0.36948532, -0.1212396 , -0.12523192, -0.6182337 ,
         0.52985793, -0.5389688 ,  0.5039901 ,  0.23112929,  0.15333128],
       [ 0.38321573,  0.6226365 ,  0.17902714,  0.09286141,  0.6192313 ,
        -0.10991275, -0.5715094 , -0

In [16]:
# Models: Composing Layers
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResnetIdentityBlock, self).__init__(name='')
        filters1, filters2, filters3 = filters
        self.conv2a = tf.keras.layers.Conv2D(filters1, (1,1))
        self.bn2a = tf.keras.layers.BatchNormalization()
        self.conv2b = tf.keras.layers.Conv2D(filters2, \
                            kernel_size, padding='same')
        self.bn2b = tf.keras.layers.BatchNormalization()
        self.conv2c = tf.keras.layers.Conv2D(filters3, (1,1))
        self.bn2c = tf.keras.layers.BatchNormalization()
    def call(self, input_tensor, training=False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training=training)
        x = tf.nn.relu(x)
        
        x = self.conv2b(x)
        x = self.bn2b(x, training=training)
        x = tf.nn.relu(x)
        
        x = self.conv2c(x)
        x = self.bn2c(x, training=training)
        
        x += input_tensor
        return tf.nn.relu(x)

In [17]:
block = ResnetIdentityBlock(1, [1,2,3])

In [18]:
print(block(tf.zeros([1,2,3,3])))
print([x.name for x in block.trainable_variables])

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block/conv2d/kernel:0', 'resnet_identity_block/conv2d/bias:0', 'resnet_identity_block/batch_normalization/gamma:0', 'resnet_identity_block/batch_normalization/beta:0', 'resnet_identity_block/conv2d_1/kernel:0', 'resnet_identity_block/conv2d_1/bias:0', 'resnet_identity_block/batch_normalization_1/gamma:0', 'resnet_identity_block/batch_normalization_1/beta:0', 'resnet_identity_block/conv2d_2/kernel:0', 'resnet_identity_block/conv2d_2/bias:0', 'resnet_identity_block/batch_normalization_2/gamma:0', 'resnet_identity_block/batch_normalization_2/beta:0']


In [19]:
# Compose layers for model
my_seq = tf.keras.Sequential(\
            [tf.keras.layers.Conv2D(1,(1,1)),
             tf.keras.layers.BatchNormalization(),
             tf.keras.layers.Conv2D(2,1,padding='same'),
             tf.keras.layers.BatchNormalization(),
             tf.keras.layers.Conv2D(3,(1,1)),
             tf.keras.layers.BatchNormalization()
            ])

In [20]:
my_seq(tf.zeros([1,2,3,3]))

<tf.Tensor: id=525, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>